# Generated by Django 5.1.14 on 2025-11-28 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('perfil', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(help_text='Nome do evento', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do evento', null=True)),
                ('regras', models.TextField(blank=True, help_text='Regras e orientações para os participantes', null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ATIVO', help_text='Status atual do evento', max_length=20)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início do evento')),
                ('data_termino', models.DateTimeField(help_text='Data e hora de término do evento')),
                ('data_encontro', models.DateTimeField(blank=True, help_text='Data e hora do ponto de encontro (se diferente do início)', null=True)),
                ('local_encontro', models.CharField(blank=True, help_text='Descrição do local de encontro (ponto de referência)', max_length=500, null=True)),
                ('grupo_whatsapp', models.URLField(blank=True, help_text='Link do grupo do WhatsApp para o evento', max_length=500, null=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto principal do evento', null=True, upload_to='images/eventos/')),
                ('foto_url', models.URLField(blank=True, help_text='URL de uma imagem hospedada externamente', null=True)),
                ('minimo_participantes', models.PositiveIntegerField(blank=True, help_text='Número mínimo de participantes para o evento acontecer', null=True)),
                ('maximo_participantes', models.PositiveIntegerField(blank=True, help_text='Número máximo de participantes (deixe em branco para ilimitado)', null=True)),
                ('aceita_participantes', models.BooleanField(default=True, help_text='Se o evento ainda está aceitando novos participantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do evento')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('endereco', models.ForeignKey(blank=True, help_text='Endereço onde o evento acontecerá', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.endereco')),
                ('organizador', models.ForeignKey(blank=True, help_text='Perfil do organizador do evento (pode ser nulo se o perfil for deletado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('CONFIRMADO', 'Confirmado'), ('LISTA_ESPERA', 'Lista de Espera'), ('CANCELADO', 'Cancelado'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='INSCRITO', help_text='Status atual da participação', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da inscrição')),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Data e hora do cancelamento', null=True)),
                ('avaliacao_host', models.PositiveSmallIntegerField(blank=True, help_text='Avaliação do host/organizador (1 a 5 estrelas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_host', models.TextField(blank=True, help_text='Comentário sobre o host/organizador do evento', null=True)),
                ('evento', models.ForeignKey(help_text='Evento ao qual a participação se refere', on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='eventos.eventos')),
                ('participante', models.ForeignKey(blank=True, help_text='Perfil do participante (pode ser nulo se conta foi deletada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes', to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='participantes',
            field=models.ManyToManyField(blank=True, help_text='Perfis dos participantes do evento', related_name='eventos_participando', through='eventos.Participacao', to='perfil.perfil'),
        ),
        migrations.AddIndex(
            model_name='participacao',
            index=models.Index(fields=['status'], name='eventos_par_status_9f0adc_idx'),
        ),
        migrations.AddIndex(
            model_name='participacao',
            index=models.Index(fields=['-data_inscricao'], name='eventos_par_data_in_0ff8e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participacao',
            unique_together={('evento', 'participante')},
        ),
        migrations.AddIndex(
            model_name='eventos',
            index=models.Index(fields=['-data_inicio'], name='eventos_eve_data_in_67d61f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventos',
            index=models.Index(fields=['status'], name='eventos_eve_status_a99e23_idx'),
        ),
    ]
