# Generated by Django 5.1.14 on 2025-11-27 23:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('perfil', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('grupo_whatsapp', models.CharField(blank=True, max_length=250, null=True)),
                ('data_inicio', models.DateTimeField(auto_now=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 11, 27, 23, 36, 2, 311646, tzinfo=datetime.timezone.utc))])),
                ('data_termino', models.DateTimeField(auto_now=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 11, 27, 23, 36, 2, 311696, tzinfo=datetime.timezone.utc))])),
                ('local_encontro', models.CharField(blank=True, max_length=500, null=True)),
                ('data_encontro', models.DateTimeField(auto_now=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 11, 27, 23, 36, 2, 311738, tzinfo=datetime.timezone.utc))])),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='images/eventos')),
                ('regras', models.CharField(blank=True, max_length=500, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to='perfil.perfil')),
                ('participantes', models.ManyToManyField(related_name='participantes', to='perfil.perfil')),
            ],
        ),
    ]
