# Generated by Django 5.1.14 on 2025-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ESPORTE', 'Esporte'), ('LAZER', 'Lazer'), ('CULTURA', 'Cultura'), ('TECNOLOGIA', 'Tecnologia'), ('EDUCACAO', 'Educação')], help_text='Categoria do evento', max_length=20, null=True),
        ),
    ]
