# Generated by Django 5.1.14 on 2025-12-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='local_encontro',
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('EDU', 'Educação'), ('ESP', 'Esporte'), ('CUL', 'Cultura'), ('OUT', 'Outros')], default='OUT', max_length=3),
        ),
        migrations.AddField(
            model_name='eventos',
            name='nome_local',
            field=models.CharField(blank=True, help_text='Nome do local de encontro (se diferente do endereço do evento)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='ponto_encontro',
            field=models.CharField(blank=True, help_text='Descrição do local de encontro (ponto de referência)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='ponto_endereco',
            field=models.CharField(blank=True, help_text='Endereço do ponto de encontro (Otimizado)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tags_input',
            field=models.CharField(blank=True, help_text='Tags para categorizar o evento', max_length=200, null=True),
        ),
    ]
