# Generated by Django 5.1.14 on 2025-12-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_eventos_local_encontro_eventos_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ponto_descricao',
            field=models.TextField(blank=True, help_text='Ex: Vou estar com uma camisa amarela. Nos encontraremos no portão principal 1 hora antes do evento começar.', null=True),
        ),
    ]
