# Generated by Django 5.1.14 on 2025-12-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_eventos_ponto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='ponto_endereco',
            new_name='local_encontro',
        ),
    ]
