# Generated by Django 5.1.14 on 2025-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
