# Generated by Django 5.1.14 on 2025-12-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
