# Generated by Django 5.1.14 on 2025-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome_do_local',
            field=models.CharField(blank=True, help_text='Nome do local (ex: Shopping Center, Parque da Cidade, etc.)', max_length=255, null=True),
        ),
    ]
